@startuml
skinparam componentStyle rectangle
skinparam rectangle {
	backgroundColor<<event>> Orange
	backgroundColor<<command>> LightBlue
	backgroundColor<<external>> Pink
	backgroundColor<<document>> Green
	backgroundColor<<invariant>> Yellow
}
component C0 <<command>> [
ABC
---
<&person> UUU
]
component C1 <<event>> [
abc
]
C0 .[#green,thickness=3].> C1
component C2 <<command>> [
DEF
---
<&person> UUU
]
C0 -[hidden]right-> C2
component C3 <<event>> [
def
]
C2 .[#green,thickness=3].> C3
component C4 <<command>> [
XXX
---
<&person> UUU
---
<&task> 1234
]
C2 -[hidden]right-> C4
component C5 <<event>> [
xxx
]
C4 .[#green,thickness=3].> C5
component C6 <<command>> [
YYY
---
<&person> UUU
---
<&task> 1234
]
C4 -[hidden]right-> C6
component C7 <<event>> [
yyy
]
C6 .[#green,thickness=3].> C7
component C8 <<command>> [
ZZZ
---
<&person> UUU
---
<&task> 1234
]
C6 -[hidden]right-> C8
component C9 <<event>> [
zzz
]
C8 .[#green,thickness=3].> C9
@enduml
