@startuml
skinparam component {
	backgroundColor<<event>> Orange
	backgroundColor<<command>> LightBlue
	backgroundColor<<external>> Pink
	backgroundColor<<document>> Green
}
component C0 <<command>> [
ABC
]
note top of C0
X
Y
end note
component C3 <<event>> [
abc
]
C0 --> C3
note bottom of C3
x
y
end note
component C6 <<document>> [
document
---
- f1
- f2
- f3
]
C3 -[hidden]-> C6
component C7 <<command>> [
DEF
]
C0 -[hidden]right-> C7
component C8 <<event>> [
def
]
C7 --> C8
@enduml
