@startuml
skinparam componentStyle rectangle
skinparam rectangle {
	backgroundColor<<event>> Orange
	backgroundColor<<command>> LightBlue
	backgroundColor<<external>> Pink
	backgroundColor<<document>> Green
	backgroundColor<<invariant>> Yellow
}
component C0 <<external>> [
A
---
- x
- y
]
component C1 <<event>> [
a
]
C0 --> C1
component C2 <<command>> [
B
]
C0 -[hidden]right-> C2
component C3 <<event>> [
b
]
C2 --> C3
@enduml
