@startuml
skinparam component {
	backgroundColor<<event>> Orange
	backgroundColor<<command>> LightBlue
	backgroundColor<<external>> Pink
	backgroundColor<<document>> Green
}
component C0 <<command>> [
ABC
]
component C1 <<event>> [
abc
]
C0 --> C1
@enduml
