@startuml
skinparam componentStyle rectangle
skinparam rectangle {
	backgroundColor<<event>> Orange
	backgroundColor<<command>> LightBlue
	backgroundColor<<external>> Pink
	backgroundColor<<document>> Green
	backgroundColor<<invariant>> Yellow
}
component C0 <<command>> [
ABC
]
note top of C0
line 1
line 2
end note
component C3 <<event>> [
abc
]
C0 .[#green,thickness=3].> C3
note bottom of C3
line a
line b
end note
component C6 <<command>> [
DEF
]
C0 -[hidden]right-> C6
component C7 <<event>> [
def
]
C6 .[#green,thickness=3].> C7
@enduml
