@startuml
skinparam componentStyle rectangle
skinparam rectangle {
	backgroundColor<<event>> Orange
	backgroundColor<<command>> LightBlue
	backgroundColor<<external>> Pink
	backgroundColor<<document>> Green
	backgroundColor<<invariant>> Yellow
}
component C0 <<command>> [
X
]
component C1 <<event>> [
x
]
C0 .[#green,thickness=3].> C1
component C3 <<command>> [
A
---
- x
- y
]
C0 -[hidden]right-> C3
component C4 <<event>> [
a
]
C3 .[#green,thickness=3].> C4
component C5 <<command>> [
B
---
- i
- j
]
C3 -[hidden]right-> C5
component C6 <<event>> [
b
]
C5 .[#green,thickness=3].> C6
component C8 <<command>> [
A1
---
- x1
- y1
]
C6 -----[hidden]-> C8
component C9 <<event>> [
a1
]
C8 .[#green,thickness=3].> C9
component C11 <<command>> [
Y
]
C5 -[hidden]right-> C11
component C12 <<event>> [
y
]
C11 .[#green,thickness=3].> C12
C0 -[#Blue]> C3
C0 -[#Blue]> C8
C5 -[#Blue]> C11
C8 -[#Blue]up-> C11
@enduml
