@startuml
skinparam component {
	backgroundColor<<event>> Orange
	backgroundColor<<command>> LightBlue
	backgroundColor<<external>> Pink
	backgroundColor<<document>> Green
}
component C0 <<command>> [
ABC
]
component C1 <<event>> [
abc
]
C0 --> C1
component C2 <<command>> [
DEF
]
C0 -[hidden]right-> C2
component C3 <<event>> [
def
]
C2 --> C3
@enduml
